### ISSUE TITLE
Investigate NuGet Package?

### ISSUE THREAD

**Issue by NoelFB** [FosterFramework/Foster#11]
I haven't used NuGet before but for a lot of people it's obviously the nicest ways to use C# projects. I've been meaning to look into how to implement/set this up but it hasn't been a priority yet. Making an issue for it to remind myself to look into it in the near future.

**Comment by NoelFB** [comment]
Created an experimental NuGet package: https://www.nuget.org/packages/FosterFramework/
This doesn't really have a release schedule right now so I'll probably just update it every now and then.

**Comment by MrBrixican** [comment]
Awesome work!

**Comment by NoelFB** [comment]
I think there's an issue where it's not copying in the C DLLs so I'll investigate that tonight, and probably merge in https://github.com/NoelFB/Foster/pull/12 at the same time.

**Comment by NoelFB** [comment]
Merged in automatic NuGet pushing. I need to look into making NuGet include the platform DLLs next. Also potentially only push to NuGet if it's actually a release tag? Right now every push tries to submit to NuGet, but only ones with actual version increments will be accepted.

**Comment by NoelFB** [comment]
Alright this should now be working on Windows & Linux, and MacOS whenever I build the native library. I've also modified the Action to run on releases instead of every push so it's not constantly running.
