### ISSUE TITLE
QOI format support

### ISSUE THREAD

**Issue by MrBrixican** [FosterFramework/Foster#25]
The [Quite OK Image Format](https://qoiformat.org/) is pretty nifty from a content pipeline perspective (even GameMaker uses it internally), and with such a complete reference c implementation it should be trivial to implement. Ideally it should attempt to intercept before/after `stb_load_from_memory()`.

**Comment by NoelFB** [comment]
I think this is a good idea. I actually thought stb_image already had QOI support, but I see they're opting not to add more image formats anymore. I'm down to add this! I'll take a look soon.

**Comment by NoelFB** [comment]
Alright, got this in with 859503e!
