### ISSUE TITLE
A transparency bug that occurs when using an Aseprite file with multiple layers.

### ISSUE THREAD

**Issue by cerealpxl** [FosterFramework/Foster#28]
Hello
I loaded an aseprite file into the project and used ``Aseprite.RenderAllFrames()`` method in the same way as in the TinyLink sample but the file i used had multiple layers and the transparency was buggy.

![transparency bug](https://github.com/NoelFB/Foster/assets/83312057/b2108655-b8d0-433f-a5c2-2161dfb1f23a)

**Comment by MrBrixican** [comment]
`Image.CopyPixels(Image source, in RectInt sourceRect, Point2? destination, Func<Color, Color, Color>? blend = null)`
seems to be wrong. `blend` is unused.

**Comment by NoelFB** [comment]
Good find! Should be fixed in 9a60fd0, looks like I had a typo and forgot to pass the parameter through.

**Comment by cerealpxl** [comment]
It's working!
![image](https://github.com/NoelFB/Foster/assets/83312057/0178e8da-5f5f-4897-9f8c-629c322b3a01)
