### ISSUE TITLE
Mesh changes

### ISSUE THREAD

**Issue by MrBrixican** [FosterFramework/Foster#4]
Hey, awesome work on this library! When I saw that you recreated it, it was a very nice surprise to start the weekend.

However, I noticed some differences from the original implementation:

- First, mesh vertex/index buffer updates use glBufferData instead of glBufferSubData when possible. This has a pretty significant performance penalty (2x slower in drawing 500k textures compared to the original library).
- In line with this, the original library provided a way to partially update buffers, an extremely useful piece of functionality that allows for some niche optimizations.
- Finally, I saw that the instance component of meshes was omitted. I haven't used instanced rendering yet, but it does feel like a good feature to have.

If these omissions were to make the initial c implementation easier and is something that you already intended to refactor at some point, please disregard this issue.

Thanks once again for working on this great library!

**Comment by NoelFB** [comment]
Hey! I think all of these are good ideas. The Instance data was something I planned to add back but I just have not actually used it yet, so it wasn't a priority. The first two issues I'd like to fix more immediately though, I didn't realize the performance issue there.

**Comment by NoelFB** [comment]
OK I've updated the Mesh API to both use `glBufferSubData` and allow an offset to upload into. I'm going to close this for now and create a new issue for eventually adding Mesh Instancing back. Thanks for the input! :)
