### ISSUE TITLE
SDL gamepads and joysticks are not closed on shutdown

### ISSUE THREAD

**Issue by theofficialgman** [FosterFramework/Foster#69]
it appears that SDL_Quit is never called and gamepads and joysticks (among other things) stay initialized after any program built off of this framework exits. this leads to memory leaks and other issues

**Comment by NoelFB** [comment]
with #70 merged in is this fixed? I assume calling `SDL_Quit` will handle gamepad/joystick uninitialization without us having to do anything.

**Comment by theofficialgman** [comment]
yes that should be all you need to do
