### ISSUE TITLE
Add some repository tags

### ISSUE THREAD

**Issue by MrBrixican** [FosterFramework/Foster#72]
Having relevant tags can help with discoverability.

Some good ones may be:

- [game-framework](https://github.com/topics/game-framework) 
- [game-engine](https://github.com/topics/game-engine)
  - well aware this is a framework, but libgdx, monogame, etc. use it
- [game-development](https://github.com/topics/game-development) 
- [gamedev](https://github.com/topics/gamedev)
- [cross-platform](https://github.com/topics/cross-platform) 
- [open-source](https://github.com/topics/open-source) 
- [graphics](https://github.com/topics/graphics) 
- [2d](https://github.com/topics/2d)
- [c-sharp](https://github.com/topics/c-sharp) 
- [csharp](https://github.com/topics/csharp) 
- [dotnet](https://github.com/topics/dotnet)

**Comment by NoelFB** [comment]
Makes sense! Done!
