### ISSUE TITLE
Vertical text alignment is slightly off

### ISSUE THREAD

**Issue by tapir2342** [FosterFramework/Foster#94]
Hi again,

I found the vertical text alignment to be slightly off when rendering text using `RenderText`  with a `maxLineWidth`.
This is also a TODO in the code. I have created [PR#93](https://github.com/FosterFramework/Foster/pull/93) for this, but still wanted to create an issue.

Before the PR:

<img width="573" alt="Screenshot 2024-06-29 at 17 56 26" src="https://github.com/FosterFramework/Foster/assets/99845707/03f9fcab-dace-44ca-8292-7e6db5d9cd1e">

After the PR:

<img width="535" alt="Screenshot 2024-06-29 at 17 57 56" src="https://github.com/FosterFramework/Foster/assets/99845707/82f18fd7-7ce6-46e3-8901-bda726b10fa5">

I have not checked / used justify as of yet.

**Comment by NoelFB** [comment]
fixed in #93
