### ISSUE TITLE
OpenGL renderer: Add function to query texture size

### ISSUE THREAD

**Issue by tapir2342** [FosterFramework/Foster#99]
Hi,

I have addressed this [TODO I found in the code](https://github.com/tapir2342/Foster/pull/1/files#diff-b2d322bc31e6923e4033e55f89a61a3b7ba03992fe897407fedce1a7257ba997L41) and created a [PR for it on my own fork](https://github.com/tapir2342/Foster/pull/1/files#diff-4bcaef7a4761a62e330d41a0b87c9beb511c3db6418e11ae06682b8e348f1fb9R421) because I'm uncertain about one aspect:
What to return in the Platform [layer when foster is not running (using `FOSTER_ASSERT_RUNNING_RET`)](https://github.com/tapir2342/Foster/pull/1/files#diff-4bcaef7a4761a62e330d41a0b87c9beb511c3db6418e11ae06682b8e348f1fb9R421). Right now, i'm returning `-1`.
Does that make sense?

If yes, I can make a proper PR for this repo.

Thank you,
Kai

**Comment by NoelFB** [comment]
yeah, I think this makes sense to me! I was considering a more generic function that could fill out a struct with many properties, but right now texture size is the only one I think we care about.

**Comment by tapir2342** [comment]
Hey, I created [PR 100](https://github.com/FosterFramework/Foster/pull/100) for this.

**Comment by NoelFB** [comment]
Awesome, this looks good! Thanks :)
